const cursos = [
    { codigo: "ADM", nome: "Administração", evasao: 33.9 },
    { codigo: "ARC", nome: "Arquitetura", evasao: 53.9 },
    { codigo: "ART", nome: "Artes Visuais", evasao: 48.3 },
    { codigo: "BIO", nome: "Biologia", evasao: 51.6 },
    { codigo: "CCO", nome: "Ciência da Computação", evasao: 44.4 },
    { codigo: "CON", nome: "Contabilidade", evasao: 72.2 },
    { codigo: "DES", nome: "Design", evasao: 34.5 },
    { codigo: "DIR", nome: "Direito", evasao: 57.3 },
    { codigo: "EDF", nome: "Educação Física", evasao: 66.1 },
    { codigo: "ECO", nome: "Economia", evasao: 48.0 },
    { codigo: "ENF", nome: "Enfermagem", evasao: 65.4 },
    { codigo: "ENGC", nome: "Engenharia Civil", evasao: 77.0 },
    { codigo: "ENGE", nome: "Engenharia Elétrica", evasao: 15.1 },
    { codigo: "FIL", nome: "Filosofia", evasao: 46.1 },
    { codigo: "FIS", nome: "Física", evasao: 56.1 },
    { codigo: "GEO", nome: "Geografia", evasao: 73.7 },
    { codigo: "HIS", nome: "História", evasao: 33.0 },
    { codigo: "JOR", nome: "Jornalismo", evasao: 45.0 },
    { codigo: "LET", nome: "Letras", evasao: 39.1 },
    { codigo: "MAT", nome: "Matemática", evasao: 68.2 },
    { codigo: "MED", nome: "Medicina", evasao: 45.9 },
    { codigo: "PUB", nome: "Publicidade e Propaganda", evasao: 18.0 },
    { codigo: "PSI", nome: "Psicologia", evasao: 27.1 },
    { codigo: "QUI", nome: "Química", evasao: 60.8 },
    { codigo: "SOC", nome: "Sociologia", evasao: 48.4 }
];

const codigosParaNomes = {
    ADM: "Administração",
    ARC: "Arquitetura",
    ART: "Artes Visuais",
    BIO: "Biologia",
    CCO: "Ciência da Computação",
    CON: "Contabilidade",
    DES: "Design",
    DIR: "Direito",
    EDF: "Educação Física",
    ECO: "Economia",
    ENF: "Enfermagem",
    ENGC: "Engenharia Civil",
    ENGE: "Engenharia Elétrica",
    FIL: "Filosofia",
    FIS: "Física",
    GEO: "Geografia",
    HIS: "História",
    JOR: "Jornalismo",
    LET: "Letras",
    MAT: "Matemática",
    MED: "Medicina",
    PUB: "Publicidade e Propaganda",
    PSI: "Psicologia",
    QUI: "Química",
    SOC: "Sociologia"
};